accounts/urls.py
from django.urls import path
from .views import SignUp, ProfileView, ProfileUpdateView, ChangePass, user_order, user_order_details
from django.contrib.auth.views import (LoginView, LogoutView, PasswordResetView,
                                       PasswordResetConfirmView, PasswordResetDoneView,
                                       PasswordResetCompleteView)

app_name = 'accounts'

urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('<int:pk>/<str:username>/', ProfileView.as_view(), name='profile_view'),
    path('<int:pk>/<str:username>/update/', ProfileUpdateView.as_view(), name='update_info'),
    path('change_password', ChangePass.as_view(), name='change_password'),
    path('user_order', user_order, name='order_list'),
    path('<int:pk>/user_order_details', user_order_details, name='order_details'),

    # RESET PASS
    path('password_reset/', PasswordResetView.as_view(
        template_name="accounts/password_reset_form.html"), name='password_reset'),

    path('password_reset_done/', PasswordResetDoneView.as_view(
        template_name="accounts/password_reset_done.html"), name='password_reset_done'),

    path('<uidb64>/<token>/password_reset_confirm/', PasswordResetConfirmView.as_view(
        template_name="accounts/password_reset_confirm.html"), name='password_reset_confirm'),

    path('password_reset_complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

blog/urls.py
from django.urls import path
from .views import (PostView, PostDetailView,
                    PostCreate, PostDelete,
                    PostUpdate, add_comment,
                    remove_comment, PostLike, post_searched)

app_name = 'blog'
urlpatterns = [
    path('', PostView.as_view(), name='blog'),
    path('post/create', PostCreate.as_view(), name='post_create'),
    path('post/<int:pk>/update', PostUpdate.as_view(), name='post_edit'),
    path('post/<int:pk>/delete', PostDelete.as_view(), name='post_delete'),
    path('post/<int:pk>/details', PostDetailView.as_view(), name='post_detail'),
    path('post/post_searched', post_searched, name='post_searched'),
    path('post/<int:pk>/post/comment', add_comment, name='post_comment'),
    path('post/<int:pk>/post/comment/remove', remove_comment, name='comment_remove'),
    path('post/<int:pk>/post/like', PostLike, name='post_like'),
]

e_commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('ecom.urls', namespace='products')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('blog/', include('blog.urls', namespace='blog')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecom/urls.py
from django.urls import path
from .views import (CartView, Checkout, add_to_cart,
                    remove_from_cart, reduce_from_cart, Checkout,
                    ProductDetailView, item_search, product_view)

app_name = 'products'

urlpatterns = [
    # path('', ProductView.as_view(), name='product_list'),
    path('', product_view, name='product_list'),
    path('<int:pk>/<str:p_or_c>/', product_view, name='cat_product'),
    path('item_search/', item_search, name='item_search'),
    path('products/details/<str:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('<int:pk>/add_to_cart', add_to_cart, name='add_to_cart'),
    path('cart/', CartView.as_view(), name='cart'),
    path('checkout/', Checkout.as_view(), name='checkout'),
    path('cart/<int:pk>/remove/', remove_from_cart, name='remove_from_cart'),
    path('cart/<int:pk>/reduce/', reduce_from_cart, name='reduce_from_cart'),
    path('cart/checkout/', Checkout.as_view(), name='checkout'),
]

ecom/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.contrib.auth import get_user_model

User = get_user_model()


class Category(models.Model):
    name = models.CharField(unique=True, max_length=50, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'categories'


class SubCategory(models.Model):
    category = models.ForeignKey(Category, related_name='sub_cat', on_delete=models.CASCADE)
    name = models.CharField(unique=True, max_length=50, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name_plural = 'sub categories'


class Product(models.Model):
    sub_cat = models.ForeignKey(SubCategory, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200)
    slug = models.SlugField(blank=True, null=True)
    description = models.TextField()
    price = models.FloatField()
    stock = models.PositiveIntegerField()
    image = models.ImageField(upload_to='ecom/photos')

    def __str__(self):
        return self.title

    def save(self):
        self.slug = slugify(self.title)
        super(Product, self).save()

    def get_absolute_url(self):
        return reverse('products:product_detail', kwargs={'slug': self.slug})


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=50, default='pending')
    products = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        # return f"{self.quantity} of {self.products.title}"
        return self.user.username

    def total_price(self):
        return self.products.price * self.quantity

    # def final_price(self):
    #     return self.total_price()


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cart_products = models.ManyToManyField(Cart, related_name='cart')
    order_status = models.BooleanField(default=False)
    order_date = models.DateTimeField(blank=True, null=True)
    order_address = models.ForeignKey('Address', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.user.username

    def get_total_price(self):
        total = 0
        for product in self.cart_products.all():
            total += product.total_price()
        return total

    class Meta:
        ordering = ['-order_date']


class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    customer_name = models.CharField(max_length=60)
    contact_no = models.CharField(max_length=14)
    street_address = models.CharField(max_length=200)
    country = models.CharField(max_length=20)
    zip = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

ecom/forms.py
from django import forms

PAYMENT_CHOICES = (
    ('s', 'Stripe'),
    ('c', 'Cash on delivery'),
)


class BillingForm(forms.Form):
    customer_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    contact_no = forms.CharField(widget=forms.NumberInput(attrs={'class': 'form-control'}))
    street_address = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    country = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    zip = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    payment = forms.ChoiceField(widget=forms.RadioSelect(), choices=PAYMENT_CHOICES)

ecom/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Product, Cart, Order, Address, Category, SubCategory
from django.views.generic import ListView, DetailView, View, TemplateView
from django.utils import timezone
from django.contrib import messages
from django.http import Http404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import BillingForm
from django.core.mail import EmailMultiAlternatives
from django.conf import settings
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.core.paginator import Paginator


# class ProductView(ListView):
#     model = Product
#     paginate_by = 8


def product_view(request, pk=None, p_or_c=None):
    if p_or_c is None:
        product_list = Product.objects.all()
    elif p_or_c == 'c':
        sub_cats = SubCategory.objects.get(pk=pk)
        product_list = sub_cats.product_set.all()
    elif p_or_c == 'p':
        product_list = []
        categories = Category.objects.get(pk=pk)
        sub_cats = categories.sub_cat.all()
        for sub_cat in sub_cats:
            product = sub_cat.product_set.all()
            product_list += product
    else:
        product_list = []
    paginator = Paginator(product_list, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'ecom/product_list.html', {'page_obj': page_obj})


class ProductDetailView(DetailView):
    model = Product


class CartView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            cart = Order.objects.get(user=self.request.user, order_status=False)
        except:
            # raise Http404
            return render(self.request, 'ecom/cart.html', {})
        else:
            context = {'objects': cart}
        return render(self.request, 'ecom/cart.html', context)


def item_search(request):
    if request.method == 'POST':
        search_item = request.POST['searched']
        if search_item != '':
            search_title = Product.objects.filter(title__icontains=search_item)
            return render(request, 'ecom/search.html', {'search_item': search_item,
                                                        'search_title': search_title})
        else:
            return redirect('products:product_list')


@login_required
def add_to_cart(request, pk):
    product = get_object_or_404(Product, pk=pk)
    order_product, created = Cart.objects.get_or_create(products=product,
                                                        user=request.user,
                                                        status='pending')
    order_qs = Order.objects.filter(user=request.user, order_status=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.cart_products.filter(products__pk=product.pk).exists():
            order_product.quantity += 1
            order_product.save()
            messages.success(request, 'Product Quantity updated')
            return redirect('products:cart')
        else:
            messages.success(request, 'Product added to the cart')
            order.cart_products.add(order_product)
            return redirect('products:product_list')
    else:
        order = Order.objects.create(user=request.user, order_date=timezone.now())
        order.cart_products.add(order_product)
        messages.success(request, 'Product added to the cart')
        return redirect('products:product_list')


@login_required
def remove_from_cart(request, pk):
    product = get_object_or_404(Product, pk=pk)
    order_product = Cart.objects.get(products=product, user=request.user, status='pending')
    order_qs = Order.objects.filter(user=request.user, order_status=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.cart_products.filter(products__pk=product.pk).exists():
            order_product.delete()
            if order.cart_products.count() == 0:
                order.delete()
            messages.info(request, 'Product Removed')
            return redirect('products:cart')
        else:
            messages.error(request, 'This product is not in your cart')
            return redirect('products:cart')
    else:
        messages.error(request, "You don't have an active order!!")
        return redirect('products:product_list')


@login_required
def reduce_from_cart(request, pk):
    product = get_object_or_404(Product, pk=pk)
    order_product = Cart.objects.get(products=product, user=request.user, status='pending')
    order_qs = Order.objects.filter(user=request.user, order_status=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.cart_products.filter(products__pk=product.pk).exists():
            if order_product.quantity > 1:
                order_product.quantity -= 1
                order_product.save()
                messages.info(request, 'Product Quantity Updated')
                # alert('updated')
                return redirect('products:cart')
            else:
                order_product.delete()
                messages.info(request, 'Product Removed')
                return redirect('products:cart')
        else:
            messages.error(request, 'This product is not in your cart')
            return redirect('products:cart')
    else:
        messages.error(request, "You don't have an active order!!")
        return redirect('products:product_list')


class Checkout(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        form = BillingForm()
        try:
            cart = Order.objects.get(user=self.request.user, order_status=False)
        except:
            raise Http404
        else:
            context = {'objects': cart, 'form': form}
        return render(self.request, 'ecom/checkout.html', context)

    def post(self, *args, **kwargs):
        form = BillingForm(self.request.POST or None)
        try:
            order = Order.objects.get(user=self.request.user, order_status=False)
            html_content = render_to_string('ecom/email_template.html',
                                            {'name': self.request.user.first_name,
                                             'orderNum': order.id})
            if form.is_valid():
                customer_name = form.cleaned_data.get('customer_name')
                contact_no = form.cleaned_data.get('contact_no')
                street_address = form.cleaned_data.get('street_address')
                country = form.cleaned_data.get('country')
                zip = form.cleaned_data.get('zip')
                payment = form.cleaned_data.get('payment')
                billing = Address(
                    user=self.request.user,
                    customer_name=customer_name,
                    contact_no=contact_no,
                    street_address=street_address,
                    country=country,
                    zip=zip,
                )
                billing.save()
                order.order_address = billing
                if payment == 'c':
                    order.order_status = True
                    order.save()
                    text_content = strip_tags(html_content)
                    subject = 'Hi, ' + self.request.user.first_name + ',' + 'ORDER PLACED SUCCESSFULLY!!',
                    order_mail = EmailMultiAlternatives(
                        subject,
                        text_content,
                        settings.EMAIL_HOST_USER,
                        ['rahamanhabib2802@gmail.com']
                    )
                    order_mail.attach_alternative(html_content, "text/html")
                    order_mail.send()
                    messages.info(self.request, 'YOUR ORDER HAS BEEN PLACED')
                    return redirect('products:product_list')
                else:
                    messages.info(self.request, 'Invalid')
                    return redirect('products:checkout')
            else:
                messages.info(self.request, 'Invalid')
                return redirect('products:checkout')
        except:
            messages.warning(self.request, 'Invalid')
            return redirect('products:cart')

ecom/templates/ecom/cart.html
{% extends 'base.html' %}
{% block content %}

<div class="col-md-4">
    <h2>CART</h2>
</div>


<div class="col-md-8 mt-5">
    <div class="container-fluid mx-auto">
        <div class="row">
            {% if objects.cart_products.all %}
            <table class="table text-light"  style="background:#0a364e;">
                <thead>
                <tr class="border-none">
                    <th>#</th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    <th>Total Price</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>

                {% for p in objects.cart_products.all %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ p.products.title }}</td>
                    <td class="qty text-center" id="qty">
                        <a href="{% url 'products:reduce_from_cart' pk=p.products.pk %}" class="float-start">
                            <i class="fas fa-minus-square mr-2 text-info"></i>
                        </a>
                        <span>{{ p.quantity }}</span>
                        <a href="{% url 'products:add_to_cart' pk=p.products.pk %}" class="float-end">
                            <i class="fas fa-plus-square ml-2 text-info"></i>
                        </a>
                    </td>

                    <td>{{ p.products.price }} BDT</td>
                    <td>{{ p.total_price }} BDT</td>
                    <td class="text-center">
                        <a href="{% url 'products:remove_from_cart' pk=p.products.pk %}" class="text-danger remove"
                           title="remove from cart">
                            <i class="fa fa-trash"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td class="text-warning">Total Amount</td>
                    <td><strong>{{ objects.get_total_price }} BDT</strong></td>
                    <td></td>
                </tr>
                </tbody>
            </table>
            <div class="ms-auto">
                <a href="{% url 'products:product_list' %}" class="btn btn-info ms-auto">Continue Shopping</a>
                <a href="{% url 'products:checkout' %}" class="btn btn-warning ms-auto">Checkout</a>
            </div>
            {% else %}
            <div class="col-md-8">
                <div class="alert alert-warning">
                    <i class="fas fa-info text-info mr-2"></i>
                    Your cart is empty
                </div>
                <a href="{% url 'products:product_list' %}" class="btn btn-info">Continue Shopping</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

ecom/templates/ecom/email_template.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>EMAIL</title>
</head>
<body>
<h3 class="text-uppercase">Hi {{ name }}</h3>
<p><span style="font-size:16px;">Gratitude!!</span> for choosing us.</p>
<p>your order has been placed successfully</p>
<h5>your order number <span class="badge bg-secondary">{{ orderNum }}</span></h5>
<p>To view details, click the below link</p>
<a href="{% url 'accounts:order_details' pk=orderNum %}">View order details</a>

<p>We will reach you soon!!</p>
<h3>Courtesy By "GEAR BOX"</h3>
</body>
</html>

ecom/templates/ecom/product_detail.html
{% extends 'base.html' %}
{% block content %}
{% if object %}
<div class="col-md-5">
    <figure class="figure">
        <img class="figure-img img-fluid" src="{{ object.image.url }}" alt="">
    </figure>
</div>

<div class="col-md-7">
    <div class="container">
        <div class="col-md-6 mb-2" style="border-left:1px solid #17a2b8;">
            <div class="ms-2">
                <h2>{{ object.title }}</h2>
                <h6>{{ object.price }} BDT</h6>
                <p><small>{{ object.description }}</small></p>
            </div>
        </div>
        <a href="{% url 'products:add_to_cart' pk=object.pk %}"
           class="text-uppercase btn btn-info btn-lg nice-btn text-light">Add to
            Cart</a>

    </div>
</div>
{% endif %}
{% endblock %}

ecom/templates/ecom/product_list.html
{% extends 'base.html' %}
{% block content %}

<div class="col-md-9 mx-auto">
    {% include 'ecom/search_item.html' %}
    <div class="container-fluid mt-5">
        <div class="row">
            {% if page_obj %}
            {% for pro in page_obj %}
            <div class="col-xs-6 col-sm-6 col-md-4 col-xl-3 mb-2" style="border-left:1px solid #17a2b8;">
                <figure class="figure">
                    <img class="figure-img img-fluid" src="{{ pro.image.url }}" alt="">
                    <figcaption>
                        <a class="text-decoration-none text-light"
                           href="{% url 'products:product_detail' slug=pro.slug  %}">
                            <div class="ms-2">
                                <h6>{{ pro.title }}</h6>
                                <h5>Price {{ pro.price }} BDT</h5>
                            </div>
                        </a>

                        <a href="{% url 'products:add_to_cart' pk=pro.pk %}"
                           class="btn btn-info btn-block nice-btn text-light">
                            add to cart
                        </a>
                    </figcaption>
                </figure>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
    <!--    pagination-->
    {% if page_obj %}
    <div class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}" class="prev"><i class="fas fa-angle-left"></i></a>
        {% endif %}
        <a href="#" class="num active">{{ page_obj.number }}</a>
        <a href="#" class="num">2</a>
        <a href="#" class="num">3</a>
        <a href="#" class="num">4</a>
        <a href="#" class="num">5</a>
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" class="next"><i class="fas fa-angle-right"></i></a>
        {% else %}
        <a href="#" class="next disabled" tabindex="-1" aria-disabled="true"><i class="fas fa-angle-right"></i></a>
        {% endif %}

        {{ page_obj.num_pages }}
    </div>
    {% endif %}
    <!--    {% if page_obj %}-->
    <!--    <nav aria-label="...">-->
    <!--        <ul class="pagination justify-content-center">-->
    <!--            {% if page_obj.has_previous %}-->
    <!--            <li class="page-item">-->
    <!--                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>-->
    <!--            </li>-->
    <!--            {% endif %}-->
    <!--            &lt;!&ndash;          <li class="page-item"><a class="page-link" href="?page=1">1</a></li>&ndash;&gt;-->
    <!--            <li class="page-item active" aria-current="page">-->
    <!--          <span class="page-link bg-info">-->
    <!--            {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}-->
    <!--              &lt;!&ndash;              of {{ page_obj.paginator.num_pages }}&ndash;&gt;-->
    <!--            <span class="sr-only">(current)</span>-->
    <!--          </span>-->
    <!--            </li>-->
    <!--            &lt;!&ndash;        <li class="page-item"><a class="page-link" href="?page=3">3</a></li>&ndash;&gt;-->
    <!--            {% if page_obj.has_next %}-->
    <!--            <li class="page-item">-->
    <!--                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>-->
    <!--                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>-->
    <!--            </li>-->
    <!--            {% endif %}-->
    <!--        </ul>-->
    <!--    </nav>-->
    <!--    {% endif %}-->
</div>

{% endblock %}

ecom/templates/ecom/search.html
{% extends 'base.html' %}
{% block content %}

<div class="com-nd-4">
    <h2>CATEGORY</h2>
</div>

<div class="col-md-8 mx-auto">
    {% include 'ecom/search_item.html' %}
    <div class="container-fluid mt-5">
        <div>You have searched for <strong>"{{ search_item }}"</strong></div>
        {% if search_title.count < 1 %}
        <div class="alert alert-warning">We have found <strong>{{ search_title.count }} search results</strong></div>
        {% else %}
        <p>we have found <strong>" {{ search_title.count }} "</strong> results</p>

        <div class="row">
            {% if search_title %}
            {% for pro in search_title %}
            <div class="col-md-4 col-sm-6 mb-2" style="border-left:1px solid #17a2b8;">
                <figure class="figure">
                    <img class="figure-img img-fluid" src="{{ pro.image.url }}" alt="">
                    <figcaption>
                        <a class="text-decoration-none text-light"
                           href="{% url 'products:product_detail' slug=pro.slug  %}">
                            <div class="ml-2">
                                <h6>{{ pro.title }}</h6>
                                <h5>Price {{ pro.price }} BDT</h5>
                            </div>
                        </a>
                        <a href="{% url 'products:add_to_cart' pk=pro.pk %}"
                           class="btn btn-info btn-block nice-btn text-light">add to cart</a>
                    </figcaption>
                </figure>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
    <!--    pagination-->
    {% if paginator %}
    <nav aria-label="...">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            </li>
            {% endif %}
            <!--          <li class="page-item"><a class="page-link" href="?page=1">1</a></li>-->
            <li class="page-item active" aria-current="page">
          <span class="page-link bg-info">
            {{ page_obj.number }}
              <!--              of {{ page_obj.paginator.num_pages }}-->
            <span class="sr-only">(current)</span>
          </span>
            </li>
            <!--        <li class="page-item"><a class="page-link" href="?page=3">3</a></li>-->
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
    {% endif %}

</div>

{% endblock %}

ecom/templates/ecom/search_item.html
        <div class="d-flex justify-content-center">
            <form action="{% url 'products:item_search' %}" method="post">
                {% csrf_token %}
                <div class="searchbar">
                    <input class="search_input text-light" type="text" name="searched" placeholder="Search item...">
                    <button class="search_icon"><i class="fas fa-search text-dark"></i></button>
                </div>
            </form>
        </div>