accounts/urls.py
from django.urls import path
from .views import SignUp, ProfileView, ProfileUpdateView, ChangePass, user_order, user_order_details
from django.contrib.auth.views import (LoginView, LogoutView, PasswordResetView,
                                       PasswordResetConfirmView, PasswordResetDoneView,
                                       PasswordResetCompleteView)

app_name = 'accounts'

urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('<int:pk>/<str:username>/', ProfileView.as_view(), name='profile_view'),
    path('<int:pk>/<str:username>/update/', ProfileUpdateView.as_view(), name='update_info'),
    path('change_password', ChangePass.as_view(), name='change_password'),
    path('user_order', user_order, name='order_list'),
    path('<int:pk>/user_order_details', user_order_details, name='order_details'),

    # RESET PASS
    path('password_reset/', PasswordResetView.as_view(
        template_name="accounts/password_reset_form.html"), name='password_reset'),

    path('password_reset_done/', PasswordResetDoneView.as_view(
        template_name="accounts/password_reset_done.html"), name='password_reset_done'),

    path('<uidb64>/<token>/password_reset_confirm/', PasswordResetConfirmView.as_view(
        template_name="accounts/password_reset_confirm.html"), name='password_reset_confirm'),

    path('password_reset_complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

blog/urls.py
from django.urls import path
from .views import (PostView, PostDetailView,
                    PostCreate, PostDelete,
                    PostUpdate, add_comment,
                    remove_comment, PostLike, post_searched)

app_name = 'blog'
urlpatterns = [
    path('', PostView.as_view(), name='blog'),
    path('post/create', PostCreate.as_view(), name='post_create'),
    path('post/<int:pk>/update', PostUpdate.as_view(), name='post_edit'),
    path('post/<int:pk>/delete', PostDelete.as_view(), name='post_delete'),
    path('post/<int:pk>/details', PostDetailView.as_view(), name='post_detail'),
    path('post/post_searched', post_searched, name='post_searched'),
    path('post/<int:pk>/post/comment', add_comment, name='post_comment'),
    path('post/<int:pk>/post/comment/remove', remove_comment, name='comment_remove'),
    path('post/<int:pk>/post/like', PostLike, name='post_like'),
]

e_commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('ecom.urls', namespace='products')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('blog/', include('blog.urls', namespace='blog')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecom/urls.py
from django.urls import path
from .views import (CartView, Checkout, add_to_cart,
                    remove_from_cart, reduce_from_cart, Checkout,
                    ProductDetailView, item_search, product_view)

app_name = 'products'

urlpatterns = [
    # path('', ProductView.as_view(), name='product_list'),
    path('', product_view, name='product_list'),
    path('<int:pk>/<str:p_or_c>/', product_view, name='cat_product'),
    path('item_search/', item_search, name='item_search'),
    path('products/details/<str:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('<int:pk>/add_to_cart', add_to_cart, name='add_to_cart'),
    path('cart/', CartView.as_view(), name='cart'),
    path('checkout/', Checkout.as_view(), name='checkout'),
    path('cart/<int:pk>/remove/', remove_from_cart, name='remove_from_cart'),
    path('cart/<int:pk>/reduce/', reduce_from_cart, name='reduce_from_cart'),
    path('cart/checkout/', Checkout.as_view(), name='checkout'),
]

accounts/models.py
from django.db import models
from django.contrib import auth


# class User(auth.models.User, auth.models.PermissionsMixin):
#     def __str__(self):
#         return '@{}'.format(self.username)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User
from django import forms


class UserForm(UserCreationForm):
    class Meta:
        fields = ['username', 'first_name', 'email', 'password1', 'password2']
        model = User

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Username'
        self.fields['first_name'].label = 'Enter Full Name'
        self.fields['email'].label = 'Enter your email'


class UserUpdateForm(UserChangeForm):
    class Meta:
        fields = ['username', 'first_name', 'email']
        model = User


class ChangePassForm(PasswordChangeForm):
    class Meta:
        fields = ['old_password', 'new_password1', 'new_password2']
        model = User

accounts/views.py
from django.shortcuts import render, get_object_or_404
from .forms import UserForm, UserUpdateForm, ChangePassForm
from django.views.generic import CreateView, TemplateView, ListView, UpdateView, DetailView, View
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from ecom.models import Order


@login_required
def user_order(request):
    u_orders = Order.objects.filter(user=request.user, order_status=True)
    return render(request, 'accounts/order_list.html', {'u_orders': u_orders})


@login_required()
def user_order_details(request, pk):
    order_details = Order.objects.get(user=request.user, pk=pk)
    print(order_details)
    return render(request, 'accounts/order_details.html', {'order_details': order_details})


class SignUp(CreateView):
    form_class = UserForm
    success_url = reverse_lazy('accounts:login')
    template_name = 'accounts/signup.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.is_active = False
        self.object.save()
        return super().form_valid(form)


class ProfileView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'accounts/user_detail.html'


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'accounts/user_form.html'
    success_url = reverse_lazy('accounts:profile_view')


class ChangePass(LoginRequiredMixin, PasswordChangeView):
    model = User
    form_class = ChangePassForm
    template_name = 'accounts/change_password_form.html'
    success_url = reverse_lazy('accounts:home')

accounts/templates/accounts/change_password_form.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
<div class="col-md-5">
    <h1>Change Password</h1>
</div>
<div class="col-md-7">
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-info btn-lg" value="Change">
    </form>
</div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
<div class="col-md-7">
    <h1>Login!!</h1>
</div>
<div class="col-md-5">
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-info btn-lg nice-btn" value="Login"><br>
        <a href="{% url 'accounts:password_reset' %}">Forgot Password</a>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/nav.html
<div class="mt-2">
      <ol class="breadcrumb text-light" style="background:transparent;">
      <li class="breadcrumb-item active ms-auto">
        <a class="text-decoration-none text-light" href="{% url 'accounts:profile_view' pk=user.pk username=user.username %}"><i class="fas fa-user me-2"></i><small>PROFILE</small></a>
    </li>
    <li class="breadcrumb-item">
        <a class="text-decoration-none text-light" href="{% url 'accounts:order_list' %}"><i class="fas fa-shopping-bag me-2"></i><small>ORDER</small></a>
    </li>
    <li class="breadcrumb-item" aria-current="page">
        <a class="text-decoration-none text-light" href="#"><i class="fas fa-chart-line me-2"></i><small>ACTIVITY</small></a>
    </li>
  </ol>
</div>

accounts/templates/accounts/order_details.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap5 %}
{% block nav %}
{% include 'accounts/nav.html' %}
{% endblock %}
{% block content %}
<div class="col-md-3">
    <h6 class="display-6">ORDER DETAILS</h6>
</div>

<div class="col-md-9">

    {% if order_details %}
    <table class="table text-light"  style="background:#0a364e;">
                <thead>
                <tr class="border-none">
                    <th>#</th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Price</th>
                    <th>Total Price</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>

                {% for p in order_details.cart_products.all %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ p.products.title }}</td>
                    <td class="">
                        <span>{{ p.quantity }}</span>
                    </td>

                    <td>{{ p.products.price }} BDT</td>
                    <td>{{ p.total_price }} BDT</td>
                    <td class="text-warning">
                        {% if order_details.order_status == False %}
                        Pending
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td class="text-warning">Total Amount</td>
                    <td><strong>{{ order_details.get_total_price }} BDT</strong></td>
                    <td></td>
                </tr>
                </tbody>
            </table>
    {% endif %}
</div>
{% endblock %}

accounts/templates/accounts/order_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap5 %}
{% block nav %}
{% include 'accounts/nav.html' %}
{% endblock %}
{% block content %}
<div class="col-md-3">
    <h4>ORDER LIST</h4>
</div>

<div class="col-md-9">
    {% if u_orders %}
    {% for o in u_orders %}


    <ol class="list-group list-group-numbered">
        <li class="list-group-item d-flex justify-content-between align-items-start" style="background:#0a364e;">
            <div class="ms-2 me-auto text-light">
                <div class="text-capitalize">order number <strong>#{{ o.id }}</strong></div>
                {{o.user.username}} <small>ordered at</small> <small class="text-muted">{{ o.order_date }}</small><br>
                <small>TOTAL <span class="text-info">{{ o.get_total_price }} BDT</span></small>
            </div>
            <span class="badge bg-warning rounded-pill">
                <a class="text-decoration-none text-dark" href="{% url 'accounts:order_details' pk=o.pk %}">Order Details</a>
            </span>
        </li>
    </ol>
    {% endfor %}
    {% else %}
        <div class="col-md-8 mx-auto">
        <p class="alert alert-secondary">
            <i class="fas fa-info text-info mr-2"></i>
            You don't have made any purchase yet!!
        </p>
        <a href="{% url 'products:product_list' %}" class="btn btn-info">Buy Some</a>
    </div>

    {% endif %}
</div>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
<div class="col-md-3">
    <h1>Reset Password</h1>
</div>
<div class="col-md-9">
    <h3>Enter new password</h3>
    <p class="">Please enter your new password twice so we can verify you typed it in correctly.</p>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-info btn-sm" value="Change my password"><br>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}
{% block content %}
<div class="col-md-8 mx-auto">
    <h3>Password reset sent</h3>
    <p>We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>
    <p>If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.</p>
</div>

{% endblock %}

accounts/templates/accounts/password_reset_form.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
<div class="col-md-3">
    <h1>Reset Password</h1>
</div>
<div class="col-md-9">
    <p class="">Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.</p>
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-info btn-sm" value="Reset My Password"><br>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
<div class="col-md-7">
    <h1>SIGN UP!!</h1>
</div>
<div class="col-md-5">
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-info btn-lg" value="Sign In">
    </form>
</div>
{% endblock %}

accounts/templates/accounts/user_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap5 %}
{% block nav %}
{% include 'accounts/nav.html' %}
{% endblock %}
{% block content %}
<div class="col-md-3">
    <h5 class="text-uppercase">Profile Info</h5>
    <div class="card" style="background:#0a364e;">
        <img src="{% static 'img/user1-128x128.jpg' %}" class="card-img-top" alt="User Image">
        <div class="card-body" style="background-color:#0a364e;">
            <h6 class="card-title text-center text-uppercase">{{ user.first_name }}</h6>
            <p class="card-text text-center">{{ user.email }}</p>
            <div class="text-center">
                <a class="btn btn-sm btn-warning mb-2" href="{% url 'accounts:update_info' username=user.username pk=user.pk %}">
                    <small class="text-uppercase"><strong>Update Info</strong></small>
                </a>
                <a href="{% url 'accounts:change_password' %}" class="btn btn-info btn-sm mb-2">
                    <small class="text-uppercase"><strong>Change Password</strong></small>
                </a>
            </div>
        </div>
    </div>
</div>

<div class="col-md-9">

</div>
{% endblock %}

accounts/templates/accounts/user_form.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
<div class="col-md-7">
    <h1 class="text-capitalize">update Profile Info</h1>
</div>
<div class="col-md-5">
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-info btn-lg" value="Update">
    </form>
</div>
{% endblock %}