accounts/urls.py
from django.urls import path
from .views import SignUp, ProfileView, ProfileUpdateView, ChangePass, user_order, user_order_details
from django.contrib.auth.views import (LoginView, LogoutView, PasswordResetView,
                                       PasswordResetConfirmView, PasswordResetDoneView,
                                       PasswordResetCompleteView)

app_name = 'accounts'

urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('<int:pk>/<str:username>/', ProfileView.as_view(), name='profile_view'),
    path('<int:pk>/<str:username>/update/', ProfileUpdateView.as_view(), name='update_info'),
    path('change_password', ChangePass.as_view(), name='change_password'),
    path('user_order', user_order, name='order_list'),
    path('<int:pk>/user_order_details', user_order_details, name='order_details'),

    # RESET PASS
    path('password_reset/', PasswordResetView.as_view(
        template_name="accounts/password_reset_form.html"), name='password_reset'),

    path('password_reset_done/', PasswordResetDoneView.as_view(
        template_name="accounts/password_reset_done.html"), name='password_reset_done'),

    path('<uidb64>/<token>/password_reset_confirm/', PasswordResetConfirmView.as_view(
        template_name="accounts/password_reset_confirm.html"), name='password_reset_confirm'),

    path('password_reset_complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

blog/urls.py
from django.urls import path
from .views import (PostView, PostDetailView,
                    PostCreate, PostDelete,
                    PostUpdate, add_comment,
                    remove_comment, PostLike, post_searched)

app_name = 'blog'
urlpatterns = [
    path('', PostView.as_view(), name='blog'),
    path('post/create', PostCreate.as_view(), name='post_create'),
    path('post/<int:pk>/update', PostUpdate.as_view(), name='post_edit'),
    path('post/<int:pk>/delete', PostDelete.as_view(), name='post_delete'),
    path('post/<int:pk>/details', PostDetailView.as_view(), name='post_detail'),
    path('post/post_searched', post_searched, name='post_searched'),
    path('post/<int:pk>/post/comment', add_comment, name='post_comment'),
    path('post/<int:pk>/post/comment/remove', remove_comment, name='comment_remove'),
    path('post/<int:pk>/post/like', PostLike, name='post_like'),
]

e_commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('ecom.urls', namespace='products')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('blog/', include('blog.urls', namespace='blog')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from ckeditor.fields import RichTextField
User = get_user_model()


class Post(models.Model):
    title = models.CharField(max_length=200)
    description = RichTextField()
    publish_date = models.DateTimeField(auto_now=True)
    post_image = models.ImageField(upload_to='post/images', blank=True, null=True)
    likes = models.ManyToManyField(User, related_name='post_likes')
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.pk})

    def total_likes(self):
        return self.likes.count()

    class Meta:
        ordering = ['-publish_date']


class PostComment(models.Model):
    text = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    comment_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.post.pk})

blog/forms.py
from django import forms
from .models import Post, PostComment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'description', 'post_image', 'user')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'user': forms.TextInput(attrs={'type': 'hidden', 'value': '', 'id': 'usr'}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = PostComment
        fields = ('text', 'user')
        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'rows': '5'}),
            'user': forms.TextInput(attrs={'type': 'hidden', 'value': '', 'id': 'usr'}),
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, PostComment
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from .forms import PostForm, CommentForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.http import Http404
from django.contrib.auth import get_user_model
User = get_user_model()


class PostView(ListView):
    model = Post
    paginate_by = 3


class PostDetailView(DetailView):
    model = Post

    def get_context_data(self, *args, **kwargs):
        context = super(PostDetailView, self).get_context_data(*args, **kwargs)
        likes = get_object_or_404(Post, id=self.kwargs['pk'])
        context['post_likes'] = likes.total_likes()
        context['users_like'] = User.objects.filter(post_likes__id=self.kwargs['pk'])
        return context


class UserPost(ListView):
    model = Post

    # def get_queryset(self):
    #     try:
    #         self.post.user = User.objects.prefetch_related('posts').get(username__ixact=self.kwargs.get('username'))
    #     except DoesNotExist:
    #         raise Http404
    #     else:
    #         return self.post_user.posts.all()
    #
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['post_user'] = self.post_user
    #     return context


class PostDelete(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:blog')


class PostCreate(LoginRequiredMixin, CreateView):
    login_url = '/accounts/login/'
    model = Post
    form_class = PostForm


def post_searched(request):
    if request.method == 'POST':
        searched = request.POST['searched']
        blog_title = Post.objects.filter(title__icontains=searched)
        blog_content = Post.objects.filter(description__icontains=searched)
        # blog_search = blog_title.union(blog_content)
        blog_search = blog_title | blog_content

        return render(request, 'blog/blog_search.html', {'searched': searched,
                                                         'blog_search': blog_search})


class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ('title', 'description')
    template_name = 'blog/post_update.html'


@login_required
def add_comment(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/comment_form.html', {'form': form})


@login_required
def remove_comment(request, pk):
    comment = get_object_or_404(PostComment,pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blog:post_detail', pk=post_pk)


@login_required
def PostLike(request, pk):
    post = get_object_or_404(Post, id=request.POST.get('p_id'))
    post.likes.add(request.user)
    return redirect('blog:blog')

blog/templates/blog/blog_search.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}

<div class="col-md-5">
    <h1 class="text-uppercase">Blog Post</h1>
    {% if user.is_authenticated %}
    <h4 class="text-warning">@{{ user.username }}</h4>
    {% else %}
    <h2 class="text-info">Please Login</h2>
    <a href="{% url 'accounts:login' %}" class="btn btn-warning btn-lg nice-btn">Login</a>
    {% endif %}

</div>
<div class="col-md-7">
    <div class="text-right d-flex justify-content-end">
        {% include 'blog/search.html' %}
        <div class="ml-2">
            <a href="{% url 'blog:post_create' %}" class="btn btn-info nice-btn text-uppercase">
                <i class="fa fa-edit"></i> Create Post
            </a>
        </div>
    </div>


    <div class="mb-3 mt-3">
        {% if searched %}
        <div>You have searched for <strong>"{{ searched }}"</strong></div>


        {% if blog_search.count < 1 %}
        <div class="alert alert-warning">We have found <strong>0 search results</strong></div>
        {% else %}
        <p>we have found <strong>" {{ blog_search.count }} "</strong> results</p>
        {% for p in blog_search %}
        <div class="card mb-3 mt-3" style="background:#0a364e;">
            <div class="row no-gutters clearfix">
                <div class="float-left">
                    <img src="{% static 'img/user1-128x128.jpg' %}" class="rounded-circle my-5 ml-3" height="40"
                         width="40"
                         alt="User Image">
                </div>
                <div class="float-left">
                    <div class="card-body" style="background-color:#0a364e;">
                        <a href="{% url 'blog:post_detail' pk=p.pk %}" class="text-light text-decoration-none">
                            <small><i>Posted By: </i><span class="text-info">{{ p.user.username }}</span></small>
                            <small>on <strong class="text-muted">{{ p.publish_date }}</strong></small>
                            <h6>{{ p.title }}</h6>
                            <p>{{ p.description|safe }}</p>


                            {% if user.is_authenticated %}
                            <div class="clearfix">
                                <form action="{% url 'blog:post_like' pk=p.pk %}" method="post">
                                    {% csrf_token %}
                                    <small>
                                        <button class="btn btn-light btn-sm float-left" type="submit" name="p_id"
                                                value="{{ p.id }}">
                                            <i class="fas  fa-thumbs-up text-info"></i> Like
                                        </button>
                                    </small>
                                </form>

                                <a href="{% url 'blog:post_comment' pk=p.pk %}"
                                   class="btn btn-info btn-sm ml-2 float-left">Comment</a>
                            </div>
                            <br>
                            {% endif %}

                            {% if user.is_authenticated and user.username == p.user.username %}
                            <small>
                                <a href="{% url 'blog:post_edit' pk=p.pk %}" class="text-info">Edit</a>
                            </small>
                            <a href="{% url 'blog:post_delete' pk=p.pk %}" class="text-danger">
                                <i class="fa fa-trash"></i>
                            </a>
                            {% endif %}
                            <p>{{ p.comments.count }} Comments</p>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        {% endfor %}

        <!--    pagination-->
        {% if paginator %}
        <nav aria-label="...">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                </li>
                {% endif %}
                <!--          <li class="page-item"><a class="page-link" href="?page=1">1</a></li>-->
                <li class="page-item active" aria-current="page">
              <span class="page-link bg-info">
                {{ page_obj.number }}
                  <!--              of {{ page_obj.paginator.num_pages }}-->
                <span class="sr-only">(current)</span>
              </span>
                </li>
                <!--        <li class="page-item"><a class="page-link" href="?page=3">3</a></li>-->
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                </li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}
        {% endif %}
         {% else %}
        <div>You have searched for Nothing</div>
        {% endif %}
    </div>
</div>
{% endblock %}

blog/templates/blog/comment_form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
<div class="col-md-7">
    <h1 class="text-uppercase">Comment</h1>
    {% if user.is_authenticated %}
    <h2 class="tex t-warning">@{{ user.username }}</h2>
    <h2 class="text-info text-uppercase"><i>Create Comment</i></h2>
    {% else %}
    <a href="{% url 'accounts:login' %}" class="btn btn-warning btn-lg">Login</a>
    {% endif %}
</div>
<div class="col-md-5">
    {% if user.is_authenticated %}
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Post Comment" class="btn btn-info btn-lg">
        <script>
            var name = "{{ user.id }}";
            document.getElementById('usr').value = name;
        </script>
    </form>
    {% endif %}
</div>
{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends 'base.html' %}
{% block content %}


<div class="col-md-7">
    <h3>Are you sure, you want to delete {{ object }}??</h3>
    <form method="post">
    {% csrf_token %}
    <input type="submit" value="DELETE" class="btn btn-danger btn-lg">
    <a class="btn btn-info btn-lg" href="{% url 'blog:post_detail' pk=object.pk %}">Cancel</a>
</form>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="col-md-5">
    <h1 class="text-uppercase">Blog Post</h1>
    {% if user.is_authenticated %}
    <h2 class="text-warning">@{{ user.username }}</h2>
    {% else %}
    <h2 class="text-info">Please Login</h2>
    <a href="{% url 'accounts:login' %}" class="btn btn-warning btn-lg">Login</a>
    {% endif %}
</div>
<div class="col-md-7">
    <div class="list-group">
        <div class="card-body">
            <a href="" class="text-light text-decoration-none">
                <h3>{{ post.title }}</h3>
                <p>{{ post.description|safe }} <br>
                    <small><i>Posted By: </i><span class="text-info">{{ post.user.username }}</span></small>
                    <br>

                    <a  href="#user_like" data-toggle="collapse">{{ post_likes }} Likes</a>
                    {% if user.is_authenticated %}
<!--                    <form action="{% url 'blog:post_like' pk=post.pk %}" method="post">-->
<!--                        {% csrf_token %}-->
<!--                        <small>-->
<!--                            <button class="btn btn-light btn-sm float-left" type="submit" name="p_id"-->
<!--                                    value="{{ post.id }}">-->
<!--                                <i class="fas fa-thumbs-up text-info"></i> Like-->
<!--                            </button>-->
<!--                        </small>-->
<!--                    </form>-->
                    <small>
                        <ul class="collapse list-unstyled" id="user_like">
                            {% for u_like in users_like %}
                            <li class="text-warning">
                                <a class="text-info text-decoration-none" href="">{{ u_like.first_name }}</a>
                            </li>
                            {% endfor %}
                        </ul>
                    </small>
                    {% endif %}
                    {% if user.is_authenticated and user.username == post.user.username %}
                        <small><a href="{% url 'blog:post_edit' pk=post.pk %}" class="text-info">Edit</a></small>
                        <small><a href="{% url 'blog:post_delete' pk=post.pk %}" class="text-danger">
                                <i class="fa fa-trash"></i>
                        </a></small>
                    {% endif %}
                </p>
            </a>

            <!--comments-->
            {% if post.comments.all %}
            <h5 class="text-warning">Comments</h5>
           {% for c in post.comments.all %}
             <div class="ml-5">
                <small>Commented By <span class="text-info">{{ c.user.username }}</span></small><br>
                <div class="ml-3">
                    <small>{{ c.text }}</small><br>
                    <small class="text-muted"><strong>{{ c.comment_date }}</strong></small>
                    {% if user.is_authenticated and user.username == c.user.username %}
                    <a href="{% url 'blog:comment_remove' pk=c.pk %}" class="text-danger">
                        <i class="fa fa-trash"></i>
                    </a>
                    {% endif %}
                </div>
            </div>
           {% endfor %}
            {% else %}
                <p>0 Comment</p>
            {% endif %}
        </div>

    </div>
</div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
<div class="col-md-5">
    <h1 class="text-uppercase">Blog Post</h1>
    {% if user.is_authenticated %}
    <h2 class="text-warning">@{{ user.username }}</h2>
    <h2 class="text-info text-uppercase"><i>Create new post</i></h2>
    {% else %}
    <a href="{% url 'accounts:login' %}" class="btn btn-warning btn-lg">Login</a>
    {% endif %}
</div>
<div class="col-md-7">
    {% if user.is_authenticated %}
    <form method="post">
        {% csrf_token %}
            {{ form.media }}
        {% bootstrap_form form %}
        <input type="submit" value="Create" class="btn btn-info btn-lg nice-btn btn-block">
        <script>
            var name = "{{ user.id }}";
            document.getElementById('usr').value = name;
        </script>
    </form>
    {% endif %}
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load staticfiles %}
 {% load humanize %}
{% block content %}

<div class="col-md-5">
    <h1 class="text-uppercase">Blog Post</h1>
    {% if user.is_authenticated %}
    <h4 class="text-warning">@{{ user.username }}</h4>
    {% else %}
    <h2 class="text-info">Please Login</h2>
    <a href="{% url 'accounts:login' %}" class="btn btn-warning btn-lg nice-btn">Login</a>
    {% endif %}

</div>
<div class="col-md-7">
    <div class="text-right d-flex justify-content-end">
        {% include 'blog/search.html' %}
        <div class="ml-2">
            <a href="{% url 'blog:post_create' %}" class="btn btn-info nice-btn text-uppercase">
                <i class="fa fa-edit"></i> Create Post
            </a>
        </div>
    </div>
    {% for p in post_list %}
    <div class="card mb-3 mt-3" style="background:#0a364e;">
        <div class="">
            <div class="float-start">
                <img src="{% static 'img/user1-128x128.jpg' %}" class="rounded-circle my-5 ms-3" height="40" width="40"
                     alt="User Image">
            </div>
            <div class="float-start">
                <div class="card-body" style="background-color:#0a364e;">
                    <a href="{% url 'blog:post_detail' pk=p.pk %}" class="text-light text-decoration-none">
                        <small><i>Posted By: </i><span class="text-info">{{ p.user.username }}</span></small>
                        <small>on <strong class="text-muted">{{ p.publish_date|naturaltime }}</strong></small>
                        <h6>{{ p.title }}</h6>
                        <p>{{ p.description|safe }}</p>


                        {% if user.is_authenticated %}
                        <div class="clearfix">
                            <form action="{% url 'blog:post_like' pk=p.pk %}" method="post">
                                {% csrf_token %}
                                <small>
                                    <button class="btn btn-light btn-sm float-start" type="submit" name="p_id"
                                            value="{{ p.id }}">
                                        <i class="fas  fa-thumbs-up text-info"></i> Like
                                    </button>
                                </small>
                            </form>

                            <a href="{% url 'blog:post_comment' pk=p.pk %}"
                               class="btn btn-info btn-sm ml-2 float-start">Comment</a>
                        </div>
                        <br>
                        {% endif %}

                        {% if user.is_authenticated and user.username == p.user.username %}
                        <small>
                            <a href="{% url 'blog:post_edit' pk=p.pk %}" class="text-info">Edit</a>
                        </small>
                        <a href="{% url 'blog:post_delete' pk=p.pk %}" class="text-danger">
                            <i class="fa fa-trash"></i>
                        </a>
                        {% endif %}
                        <p>{{ p.comments.count }} Comments</p>
                    </a>
                </div>
            </div>
        </div>
    </div>

    {% endfor %}

    <!--    pagination-->
    {% if paginator %}
    <nav aria-label="...">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
            </li>
            {% endif %}
            <!--          <li class="page-item"><a class="page-link" href="?page=1">1</a></li>-->
            <li class="page-item active" aria-current="page">
          <span class="page-link bg-info">
            {{ page_obj.number }}
              <!--              of {{ page_obj.paginator.num_pages }}-->
            <span class="sr-only">(current)</span>
          </span>
            </li>
            <!--        <li class="page-item"><a class="page-link" href="?page=3">3</a></li>-->
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>
{% endblock %}

blog/templates/blog/post_update.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
<div class="col-md-5">
    <h1 class="text-uppercase">Blog Post</h1>
    {% if user.is_authenticated %}
    <h2 class="text-warning">@{{ user.username }}</h2>
    <h2 class="text-info text-uppercase"><i>Update post</i></h2>
    {% else %}
    <a href="{% url 'accounts:login' %}" class="btn btn-warning btn-lg">Login</a>
    {% endif %}
</div>
<div class="col-md-7">
    {% if user.is_authenticated and user.id == object.user.id %}
    <form method="post">
        {% csrf_token %}
        {{ form.media }}
        {% bootstrap_form form %}
        <input type="submit" value="Update" class="btn btn-info btn-lg">
        <script>
            var name = "{{ user.id }}";
            document.getElementById('usr').value = name;
        </script>
    </form>
    {% else %}
    <div class="alert alert-danger">
        <p>You have no authority!!</p>
    </div>
    {% endif %}
</div>
{% endblock %}

blog/templates/blog/search.html
        <div class="d-flex justify-content-center">
            <form action="{% url 'blog:post_searched' %}" method="post">
                {% csrf_token %}
                <div class="searchbar">
                    <input class="search_input text-light" type="text" name="searched" placeholder="Search...">
                    <button class="search_icon"><i class="fas fa-search text-dark"></i></button>
                </div>
            </form>
        </div>