accounts/urls.py
from django.urls import path
from .views import SignUp, ProfileView, ProfileUpdateView, ChangePass, user_order, user_order_details
from django.contrib.auth.views import (LoginView, LogoutView, PasswordResetView,
                                       PasswordResetConfirmView, PasswordResetDoneView,
                                       PasswordResetCompleteView)

app_name = 'accounts'

urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('<int:pk>/<str:username>/', ProfileView.as_view(), name='profile_view'),
    path('<int:pk>/<str:username>/update/', ProfileUpdateView.as_view(), name='update_info'),
    path('change_password', ChangePass.as_view(), name='change_password'),
    path('user_order', user_order, name='order_list'),
    path('<int:pk>/user_order_details', user_order_details, name='order_details'),

    # RESET PASS
    path('password_reset/', PasswordResetView.as_view(
        template_name="accounts/password_reset_form.html"), name='password_reset'),

    path('password_reset_done/', PasswordResetDoneView.as_view(
        template_name="accounts/password_reset_done.html"), name='password_reset_done'),

    path('<uidb64>/<token>/password_reset_confirm/', PasswordResetConfirmView.as_view(
        template_name="accounts/password_reset_confirm.html"), name='password_reset_confirm'),

    path('password_reset_complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

blog/urls.py
from django.urls import path
from .views import (PostView, PostDetailView,
                    PostCreate, PostDelete,
                    PostUpdate, add_comment,
                    remove_comment, PostLike, post_searched)

app_name = 'blog'
urlpatterns = [
    path('', PostView.as_view(), name='blog'),
    path('post/create', PostCreate.as_view(), name='post_create'),
    path('post/<int:pk>/update', PostUpdate.as_view(), name='post_edit'),
    path('post/<int:pk>/delete', PostDelete.as_view(), name='post_delete'),
    path('post/<int:pk>/details', PostDetailView.as_view(), name='post_detail'),
    path('post/post_searched', post_searched, name='post_searched'),
    path('post/<int:pk>/post/comment', add_comment, name='post_comment'),
    path('post/<int:pk>/post/comment/remove', remove_comment, name='comment_remove'),
    path('post/<int:pk>/post/like', PostLike, name='post_like'),
]

e_commerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    path('', include('ecom.urls', namespace='products')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('blog/', include('blog.urls', namespace='blog')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecom/urls.py
from django.urls import path
from .views import (CartView, Checkout, add_to_cart,
                    remove_from_cart, reduce_from_cart, Checkout,
                    ProductDetailView, item_search, product_view)

app_name = 'products'

urlpatterns = [
    # path('', ProductView.as_view(), name='product_list'),
    path('', product_view, name='product_list'),
    path('<int:pk>/<str:p_or_c>/', product_view, name='cat_product'),
    path('item_search/', item_search, name='item_search'),
    path('products/details/<str:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('<int:pk>/add_to_cart', add_to_cart, name='add_to_cart'),
    path('cart/', CartView.as_view(), name='cart'),
    path('checkout/', Checkout.as_view(), name='checkout'),
    path('cart/<int:pk>/remove/', remove_from_cart, name='remove_from_cart'),
    path('cart/<int:pk>/reduce/', reduce_from_cart, name='reduce_from_cart'),
    path('cart/checkout/', Checkout.as_view(), name='checkout'),
]

templates/base.html
<!doctype html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>GearBoX BD</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!--    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" rel="stylesheet">-->
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    {% block style %}{% endblock %}
</head>

<body>

<nav>
    <ol class="breadcrumb justify-content-end m-3">
        {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link text-light" href="{% url 'products:cart' %}">Cart</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-light" href="{% url 'accounts:profile_view' username=user.username pk=user.pk %}">My Account</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-light" href="{% url 'accounts:logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link text-light" href="{% url 'accounts:signup' %}">Sign Up</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-light" href="{% url 'accounts:login' %}">Login</a>
        </li>
        {% endif %}
    </ol>
</nav>

<!--<nav class="navbar navbar-expand-lg navbar-dark" style="background:#0a364e;">-->
<!--    <a class="navbar-brand text-uppercase" href="{% url 'products:product_list' %}">-->
<!--        <img class="bg-light img-fluid" src="{% static 'img/gbox.png' %}" height="50" width="50" alt="">-->
<!--    </a>-->
<!--    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#down"-->
<!--            aria-expanded="false" aria-label="Toggle navigation">-->
<!--        <span class="navbar-toggler-icon"></span>-->
<!--    </button>-->
<!--    <div class="collapse navbar-collapse" id="down">-->
<!--        <ul class="navbar-nav mx-auto text-uppercase">-->
<!--            <li class="nav-item active">-->
<!--                <a class="nav-link" href="{% url 'products:product_list' %}">Home <span class="sr-only">(current)</span></a>-->
<!--            </li>-->

<!--            &lt;!&ndash;            <li class="nav-item">&ndash;&gt;-->
<!--            &lt;!&ndash;                <a class="nav-link" href="{% url 'products:product_list' %}">Products</a>&ndash;&gt;-->
<!--            &lt;!&ndash;            </li>&ndash;&gt;-->
<!--            <li class="nav-item">-->
<!--                <a class="nav-link" href="{% url 'blog:blog' %}">Blog</a>-->
<!--            </li>-->

<!--            {% if user.is_authenticated %}-->
<!--            <li class="nav-item">-->
<!--                <a class="nav-link" href="{% url 'products:cart' %}">CART</a>-->
<!--            </li>-->
<!--            <li class="nav-item">-->
<!--                <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>-->
<!--            </li>-->
<!--            {% else %}-->
<!--            <li class="nav-item">-->
<!--                <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>-->
<!--            </li>-->
<!--            <li class="nav-item">-->
<!--                <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>-->
<!--            </li>-->
<!--            {% endif %}-->
<!--        </ul>-->
<!--        {% if user.is_authenticated %}-->


<!--        <div class="d-flex me-5">-->
<!--            <ul class="navbar-nav ">-->
<!--                <li class="nav-item">-->
<!--                    <a href="{% url 'accounts:profile_view' username=user.username pk=user.pk %}"-->
<!--                       class="nav-link text-uppercase" title="View Profile">-->
<!--                        {{ user.username }}-->
<!--                    </a>-->
<!--                </li>-->
<!--            </ul>-->
<!--        </div>-->


<!--        {% endif %}-->
<!--    </div>-->
<!--</nav>-->


<nav style="background:#0a364e;">
    <div class="wrapper">
        <div class="logo"><a href="{% url 'products:product_list' %}">GEAR BOX</a></div>
        <input type="radio" name="slider" id="menu-btn">
        <input type="radio" name="slider" id="close-btn">
        <ul class="nav-links text-center">
            <label for="close-btn" class="btn close-btn"><i class="fas fa-times"></i></label>
            <li><a href="{% url 'products:product_list' %}">Home</a></li>
            <li>
                <a href="#" class="desktop-item">Categories</a>
                <input type="checkbox" id="showMega">
                <label for="showMega" class="mobile-item">Categories</label>
                <div class="mega-box">
                    <div class="content">
                        <div class="row">
                            <img src="img.jpg" alt="">
                        </div>
                        {% for cat in categories %}
                        <div class="row">
                            <header>
                                <a class="text-decoration-none"
                                   href="{% url 'products:cat_product' p_or_c='p' pk=cat.pk %}">
                                    {{ cat.name }}
                                </a>
                            </header>

                            {% for sub_cat in cat.sub_cat.all %}
                            <ul class="mega-links">
                                <li>
                                    <a class="text-decoration-none"
                                       href="{% url 'products:cat_product' p_or_c='c' pk=sub_cat.pk %}">
                                        {{sub_cat.name}}
                                    </a>
                                </li>
                            </ul>
                            {% endfor %}
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </li>
            <li class="nav-item"><a href="{% url 'blog:blog' %}">Blog</a></li>
        </ul>
        <label for="menu-btn" class="btn menu-btn"><i class="fas fa-bars"></i></label>
    </div>
</nav>


<div class="position-absolute top-0 end-0 p-3">
    <div class="toast align-items-center text-white bg-success border-0"
         role="alert" aria-live="assertive"
         aria-atomic="true" data-bs-delay="3000">

        <div class="d-flex">
            {% for message in messages %}
            <div class="toast-body">
                {{ message }}
            </div>
            <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast"
                    aria-label="Close"></button>
            {% endfor %}
        </div>
    </div>
</div>

<div class="container">
    {% block nav %}{% endblock %}
    <!--    <div class="mx-auto">-->
    <!--        {% if messages %}-->
    <!--        <ul class="messages">-->
    <!--            {% for message in messages %}-->
    <!--            <li {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>{{ message }}</li>-->
    <!--            {% endfor %}-->
    <!--        </ul>-->
    <!--        {% endif %}-->
    <!--    </div>-->


    <div class="row mt-5">
        {% block content %}{% endblock %}
    </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script>
    $(document).ready(function(){
        $(".toast").toast("show");
    });





</script>
{% block js %}{% endblock %}
</body>
</html>